airflow: #nom de la db
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: airflow
      password: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 1
      keepalives_idle: 0
      sslmode: prefer
      connect_timeout: 10

#parametre de connection a la base de donnees